[package]
name = "token-program"
version = "0.0.0"
edition = "2021"
readme = "./README.md"
license = "Apache-2.0"
#repository = { workspace = true }
publish = false

[package.metadata.solana]
program-id = "PToken1111111111111111111111111111111111111"

[lib]
crate-type = ["cdylib"]

[features]
logging = []
test-sbf = []

[dependencies]
pinocchio = { path = "../../../pinocchio/sdk/pinocchio" }
pinocchio-log = { path = "../../../pinocchio/sdk/log/crate" }
token-interface = { version = "^0", path = "../interface" }

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "~1.18"
solana-sdk = "~1.18"
spl-token = { version="^4", features=["no-entrypoint"] }
test-case = "3.3.1"
